### PR TITLE
compile with android-studio.

### PR DESCRIPTION
**Pull request by talregev**

### CODE REVIEW

**Comment by stonier** [comment]
I cherry-picked some of this and some also went in earlier when integrating #64 from @dwlee.

The biggest changes were from your fixes to the graveyard code. That is `application_management` and `robot_remocon`. I dropped them complete from the indigo branch - they have been replaced by 
`common_tools` and `rocon_remocon` - see comment above.

Are you still using `application_management` and `robot_remocon` in your work?

**Comment by talregev** [comment]
> Are you still using application_management and robot_remocon in your work?

i don't rememver witch project i use for application_management , i will check and give you an answer.
in the meanwhile it ok it stay on github?
why you don't want to support application_management?

there are two application_management. one is on rosjava (on android_remocons) that using old messages. 
and one [here](https://github.com/robotics-in-concert/android_remocons/tree/3rd_milestone/graveyard), that using new messages.

i think need to keep them both. one after another, and make a jars for them in the maven.

**Comment by stonier** [comment]
For turtlebot development we had some upgrades. These were to shift complexity away from the android program:
- `application_management` (hydro) upgraded to `common_tools` (indigo)
- `robot_remocon` (hydro) upgraded to `rocon_remocon` (indigo)

I can understand if people have projects relying on `application_management` and don't have time to move their current code. Having that code in this repository though would get confusing. Perhaps a better idea is to have it in a new repository on its own? e.g. `android_apps_legacy`?

**Comment by talregev** [comment]
> I can understand if people have projects relying on application_management and don't have time to move their current code. Having that code in this repository though would get confusing. Perhaps a better idea is to have it in a new repository on its own? e.g. android_apps_legacy?

I understand it now.

> e.g. android_apps_legacy?

it will be good idea, we can compile it and upload it as library to online maven  repo

**Comment by stonier** [comment]
Would you like to build the repo? If you wish, we can move it in here once its ready or we can just link people to it from Readme's and the ros wiki.

**Comment by stonier** [comment]
> please add: defaultTasks 'assembleRelease', 'uploadArchives'

Done.

**Comment by talregev** [comment]
> Would you like to build the repo?

I want. but not now, it will take a time.

**Pull request closed without merging**
